### ISSUE TITLE
ceylon2java should translate These.CONSTANT_NAMES to These.constantNames

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.tool.converter.java2ceylon#19]
java2ceylon should now do the same transformation that the model loader does.

**Comment by gavinking** [comment]
@rohitmohan96 Thank you!!

@FroMage do you have some utility method somewhere that Rohit could have used instead of writing his own function to transform SHOUTY_CASE to camelCase?

**Comment by rohitmohan96** [comment]
I actually took that from [NamingBase.java](https://github.com/ceylon/ceylon/blob/master/model/src/com/redhat/ceylon/model/loader/NamingBase.java). I just changed the parameter from `int[]` to `char[]`. I also had to make some changes to `is_CONSTANT_CASE()`.

**Comment by bjansen** [comment]
It's tricker than just converting cases, because for example `.\iSTRING` should not become `.string`, which is the `toString()` method. There are other scenarios which can cause conflicts, but they are more difficult to detect (for example a field named `FOO` should not be transformed if there's already a method `foo()`).

**Comment by gavinking** [comment]
> I actually took that from [NamingBase.java](https://github.com/ceylon/ceylon/blob/master/model/src/com/redhat/ceylon/model/loader/NamingBase.java).

OK, I guess you don't have a dependency the ceylon-model.

> There are other scenarios which can cause conflicts

I think it's OK if we have a handful of broken corner cases.
